version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.16
    - image: tiltdev/tilt:latest
    steps:
    - checkout
    - setup_remote_docker:
        version: 19.03.12
    - run:
        command: ls -all && pwd && cat .git/config
    - run:
        command: make
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/golang:1.16
#       - image: tiltdev/tilt:latest
# 
#     steps:
#       - checkout
#       - setup_remote_docker:
#           version: 19.03.12
#       - run: ls -all && pwd && cat .git/config
#       - run: make # pull and build dependencies for the project
#       # - run: ctlptl create cluster kind --registry=ctlptl-registry && test/test.sh