version: 2.1
jobs:
  build:
    docker:
      - image: tiltdev/tilt:latest

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Create kind cluster and run tilt
          command: |
            scripts/create-cluster.sh
            scripts/tilt.sh
      - run:
          name: Teardown kind cluster
          when: always
          command: scripts/teardown-cluster.sh
